<a href="https://colab.research.google.com/github/YelizavetaP/NN2022labs/blob/main/lab2/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Лабораторна робота 2
з дисципліни "Нейронні мережі" <br>
студентки 3 курсу КН ФІТ<br>
Поповаї Єлизавети

#За матеріалами [2] ознайомитись із засадами бібліотеки TensorFlow:
- засвоєння поняття тензору
- знати різні способи створення тензорів
- створити набір даних із заданим розподілом (розподіл та розмір за власним рішенням), визначити його властивості (shape, rank, size, axis)
- продемонструвати основні математичні операції над тензорами
- провести CRUD операції над даними, reshape, інтеграцію з np.array, pd.DataFrame)


In [ ]:
import tensorflow as tf
print(tf.__version__)

scalar = tf.constant(7)
print(scalar)
print(scalar.ndim)

# vector
vector = tf.constant([10, 10])
print(vector)
print(vector.ndim)

# matrix
matrix = tf.constant([[1, 2],
                      [3, 4]], dtype = tf.float16)
print(matrix)
print(matrix.ndim)

# tensor
tensor = tf.constant([[[1, 2],
                      [3, 4]],
                     
                     [[5, 6],
                      [7, 8]],
                     
                     [[9, 10],
                      [11, 12]]])
print(tensor)
print(tensor.ndim)

changeable_tensor = tf.Variable([10, 7])
print(changeable_tensor)
changeable_tensor[0].assign(7)
print(changeable_tensor)

# random
random_t = tf.random.Generator.from_seed(42) 
random_t = random_t.normal(shape=(5, 5))  
print(random_t)

# shuffle
tf.random.shuffle(random_t)

ones = tf.ones(shape=(3,2,2))
print(ones)

In [ ]:
import tensorflow as tf

tensor = tf.random.normal(shape=(4, 4, 4, 4, 3))

print('shape ',tensor.shape)
print('rank ',tensor.ndim)
print('size ', tf.size(tensor).numpy())
print('elements of 0 axis ', tensor.shape[0])


print(tensor[:2, :2, :2, :2, :2])
# ten = tensor[..., tf.newaxis]
# print(ten)


In [ ]:
import tensorflow as tf
tensor = tf.Variable([[2, 10],
                     [14, 22]])

print('+ \n', tensor + 15)
print('* \n',tensor * 3)
print('- \n',tensor - 10)
print()

print('matrix \n', tf.matmul(tensor, tensor))
tensor_1 = tf.constant([[1,2,3],
                        [4,10,1]])
mult = tensor @ tensor_1
print('@ \n', mult)
print('transpose \n', tf.transpose(mult))
print('reshape \n', tf.reshape(mult, shape=(3, 2)))



print(tensor)

In [ ]:
import numpy as np
import tensorflow as tf

# np array to tensor
np_array = np.arange(1,17)
tensor = tf.constant(np_array, shape=(2, 2, 4))

print(np_array)
print(tensor, type(tensor))
print()

# tensor ty np
t = tf.constant([[1, 2],
                 [3, 4]])
arr = np.array(t)
# arr = t.numpy()
print(arr, type(arr))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]], shape=(2, 2, 4), dtype=int64) <class 'tensorflow.python.framework.ops.EagerTensor'>

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


#Висновок
У ході лабораторної роботи я ознайомилася з функціоналом бібліотеки TensorFlow та її можливостями.